# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  unitTestPath: 'UnitTests/UnitTests.csproj'

  jobs:
  - job: Build
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
  - job: UnitTest
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
    - script: dotnet test $(unitTestPath)